# Generated by Django 4.0.2 on 2022-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_user_accountnumber_user_companyaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
