# Generated by Django 4.0.2 on 2022-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='descript',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clients',
            name='qty',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clients',
            name='rate',
            field=models.JSONField(default=dict),
        ),
    ]
