# Generated by Django 4.0.2 on 2022-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_clients_descript_alter_clients_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='amount',
            field=models.JSONField(default=dict),
        ),
    ]
