# Generated by Django 4.0.2 on 2022-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_clients_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
