# Generated by Django 4.0.2 on 2022-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='clientEmail',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='dueDate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clients',
            name='vat',
            field=models.FloatField(default=0),
        ),
    ]
