# Generated by Django 4.0.2 on 2022-03-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_clients_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='amount',
        ),
    ]
