# Generated by Django 4.0.2 on 2022-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_clients_clientemail_clients_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='subTotal',
            field=models.FloatField(default=0),
        ),
    ]
