# Generated by Django 4.0.2 on 2022-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_clients_date_alter_clients_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
