# Generated by Django 4.0.2 on 2022-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_clients_descript_remove_clients_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.DateField(auto_now_add=True, default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='dueDate',
            field=models.DateField(default=2023),
        ),
    ]
