# Generated by Django 4.0.2 on 2022-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_clients_date_clients_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.DateField(default=2022),
        ),
    ]
