# Generated by Django 4.0.2 on 2022-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_clients_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
