# Generated by Django 4.0.2 on 2022-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_clients_date_alter_clients_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='dueDate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
