# Generated by Django 4.0.2 on 2022-03-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_clients_date_alter_clients_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='date',
            new_name='createDate',
        ),
    ]
